const d = (days: number) => new Date(Date.now() + days * 864e5).toISOString()

const skate = [
  { id: 101, title: 'ОЛЛИ НА ПРЕПЯТСТВИЕ', trickName: 'OLLIE',        difficulty: 'beginner',     description: 'Запрыгни олли на любой бордюр или ступеньку. Приземление на оба колеса, контроль доски обязателен.', prizePoints: 100, category: 'skate', status: 'active', endsAt: d(5),  creator: { username: 'KickOn' },   _count: { submissions: 34 } },
  { id: 102, title: 'КИКФЛИП ЧИСТЫЙ',      trickName: 'KICKFLIP',     difficulty: 'intermediate', description: 'Полный кикфлип с чистым кэтчем в воздухе. Доска должна сделать ровно один оборот.',                  prizePoints: 150, category: 'skate', status: 'active', endsAt: d(3),  creator: { username: 'Danya_SK8' },   _count: { submissions: 21 } },
  { id: 103, title: 'ХИЛФЛИП В ДВИЖЕНИИ',  trickName: 'HEELFLIP',     difficulty: 'intermediate', description: 'Хилфлип в движении без остановки. Оценивается амплитуда, скорость и приземление.',                   prizePoints: 150, category: 'skate', status: 'active', endsAt: d(7),  creator: { username: 'mxm_ride' },    _count: { submissions: 18 } },
  { id: 104, title: 'ГРИНД НА ПОРЕБРИКЕ',  trickName: '50-50 GRIND',  difficulty: 'intermediate', description: '50-50 гринд на бордюре минимум 1 метр. Заезд и выезд считаются частью трюка.',                       prizePoints: 200, category: 'skate', status: 'active', endsAt: d(4),  creator: { username: 'Pavel_Boards' }, _count: { submissions: 12 } },
  { id: 105, title: 'МАНУАЛ 5 МЕТРОВ',     trickName: 'MANUAL',       difficulty: 'advanced',     description: 'Мануал на задних колёсах не менее 5 метров без касания. Линия должна быть прямой.',                   prizePoints: 250, category: 'skate', status: 'active', endsAt: d(6),  creator: { username: 'kira_skates' }, _count: { submissions: 8  } },
  { id: 106, title: 'ИМПОССИБЛ PRO',       trickName: 'IMPOSSIBLE',   difficulty: 'pro',          description: 'Чистый импоссибл — доска обкручивается вокруг задней ноги. Только для продвинутых.',                 prizePoints: 300, category: 'skate', status: 'active', endsAt: d(10), creator: { username: 'Anya_Roll' },   _count: { submissions: 5  } },
  { id: 107, title: 'ТРЮК В ПАРКЕ',        trickName: 'PARK TRICK',   difficulty: 'beginner',     description: 'Любой трюк в скейт-парке на рампе или боулу. Главное — уверенность и стиль.',                        prizePoints: 80,  category: 'skate', status: 'active', endsAt: d(8),  creator: { username: 'Roma_Sk8' },    _count: { submissions: 47 } },
  { id: 108, title: 'HEELFLIP ПО УЛИЧКЕ', trickName: 'STREET HEEL',  difficulty: 'advanced',     description: 'Хилфлип в уличных условиях — по пандусу, съезду или через лайн.',                                   prizePoints: 220, category: 'skate', status: 'active', endsAt: d(2),  creator: { username: 'Vlad_Stunt' }, _count: { submissions: 9  } },
]

const bmx = [
  { id: 201, title: 'БАННИ-ХОП НА БОРДЮР',  trickName: 'BUNNY HOP',        difficulty: 'beginner',     description: 'Запрыгни на бордюр банни-хопом на обоих колёсах одновременно. Удержи баланс после приземления.',      prizePoints: 100, category: 'bmx', status: 'active', endsAt: d(5),  creator: { username: 'serg_bmx' },   _count: { submissions: 29 } },
  { id: 202, title: 'МЭН-ЮАЛ НА АСФАЛЬТЕ',  trickName: 'MANUAL',           difficulty: 'beginner',     description: 'Мануал на заднем колесе не менее 10 метров по ровной поверхности.',                                   prizePoints: 120, category: 'bmx', status: 'active', endsAt: d(4),  creator: { username: 'igor_bmx' },   _count: { submissions: 18 } },
  { id: 203, title: 'БАР СПИН 180°',        trickName: 'BAR SPIN',         difficulty: 'intermediate', description: 'Полный оборот руля в прыжке — руки возвращаются на руль до приземления. Снимай в прыжке целиком.',   prizePoints: 200, category: 'bmx', status: 'active', endsAt: d(6),  creator: { username: 'serg_bmx' },   _count: { submissions: 14 } },
  { id: 204, title: 'ТЕЙЛВИП НА РАМПЕ',     trickName: 'TAILWHIP',         difficulty: 'intermediate', description: 'Рама делает полный оборот вокруг вилки. Прыжок с рампы, обе ноги снимаются с педалей.',               prizePoints: 250, category: 'bmx', status: 'active', endsAt: d(3),  creator: { username: 'igor_bmx' },   _count: { submissions: 9  } },
  { id: 205, title: '360 В ПРЫЖКЕ',          trickName: '360 JUMP',         difficulty: 'advanced',     description: 'Полный разворот байка на 360° в воздухе. Приземление уверенное, обе ноги на педалях.',                prizePoints: 300, category: 'bmx', status: 'active', endsAt: d(8),  creator: { username: 'serg_bmx' },   _count: { submissions: 6  } },
  { id: 206, title: 'БАР-ТУ-ТЕЙЛ PRO',      trickName: 'BAR TO TAILWHIP',  difficulty: 'pro',          description: 'Бар-спин + тейлвип в одном прыжке. Экстремальный трюк только для опытных.',                          prizePoints: 400, category: 'bmx', status: 'active', endsAt: d(12), creator: { username: 'igor_bmx' },   _count: { submissions: 2  } },
]

const rollers = [
  { id: 301, title: 'КРОССОВЕР НА СКОРОСТИ', trickName: 'CROSSOVER',         difficulty: 'beginner',     description: 'Скрещивание ног в движении на скорости минимум 15 км/ч. Оценивается плавность и ритм.',                prizePoints: 80,  category: 'rollers', status: 'active', endsAt: d(5),  creator: { username: 'alina_roll' }, _count: { submissions: 22 } },
  { id: 302, title: 'СОУЛ ГРИНД НА РЕЙЛЕ',   trickName: 'SOUL GRIND',        difficulty: 'intermediate', description: 'Soul grind на любом рейле или бордюре. Одна нога горизонтально, вторая в H-позиции.',                prizePoints: 180, category: 'rollers', status: 'active', endsAt: d(4),  creator: { username: 'vera_roll' },  _count: { submissions: 11 } },
  { id: 303, title: 'ПРЫЖОК ЧЕРЕЗ БАРЬЕР',    trickName: 'JUMP',              difficulty: 'beginner',     description: 'Прыжок на роликах через конус или барьер высотой от 30 см. Приземление на оба ролика.',                prizePoints: 100, category: 'rollers', status: 'active', endsAt: d(6),  creator: { username: 'alina_roll' }, _count: { submissions: 31 } },
  { id: 304, title: 'ROYALE ГРИНД',           trickName: 'ROYALE GRIND',      difficulty: 'advanced',     description: 'Royale grind — обе ноги на рейле, передняя в torque-позиции. Минимум 1 метр.',                       prizePoints: 260, category: 'rollers', status: 'active', endsAt: d(7),  creator: { username: 'vera_roll' },  _count: { submissions: 7  } },
  { id: 305, title: 'MISTY FLIP',             trickName: 'MISTY FLIP',        difficulty: 'pro',          description: 'Misty flip с рампы — диагональный сальто. Только для продвинутых агрессив-роллеров.',                prizePoints: 350, category: 'rollers', status: 'active', endsAt: d(10), creator: { username: 'alina_roll' }, _count: { submissions: 3  } },
]

const scooter = [
  { id: 401, title: '180° ПРЫЖОК',            trickName: '180 JUMP',         difficulty: 'beginner',     description: 'Разворот на 180° в прыжке на самокате. Полный оборот, уверенное приземление.',                        prizePoints: 90,  category: 'scooter', status: 'active', endsAt: d(5),  creator: { username: 'oleg_scoot' }, _count: { submissions: 38 } },
  { id: 402, title: 'ХЭНДЛБАР СПИН',          trickName: 'HIC SPIN',         difficulty: 'beginner',     description: 'Вращение руля на 180° в прыжке, ноги остаются на деке. Базовый уровень управления.',                  prizePoints: 110, category: 'scooter', status: 'active', endsAt: d(3),  creator: { username: 'oleg_scoot' }, _count: { submissions: 24 } },
  { id: 403, title: 'ТЕЙЛВИП',                trickName: 'TAILWHIP',         difficulty: 'intermediate', description: 'Тейлвип — дека делает полный оборот вокруг вилки. Ноги возвращаются до приземления.',                prizePoints: 200, category: 'scooter', status: 'active', endsAt: d(6),  creator: { username: 'oleg_scoot' }, _count: { submissions: 16 } },
  { id: 404, title: 'БАР СПИН + ТЕЙЛВИП',     trickName: 'BARSPIN TAILWHIP', difficulty: 'advanced',     description: 'Комбо в одном прыжке: бар спин + тейлвип. Оценивается синхронность и чистота приземления.',           prizePoints: 300, category: 'scooter', status: 'active', endsAt: d(8),  creator: { username: 'oleg_scoot' }, _count: { submissions: 8  } },
  { id: 405, title: 'ДВОЙНОЙ ТЕЙЛВИП PRO',    trickName: 'DOUBLE TAILWHIP',  difficulty: 'pro',          description: 'Два полных оборота деки в одном прыжке. Требует значительной высоты и контроля.',                    prizePoints: 380, category: 'scooter', status: 'active', endsAt: d(11), creator: { username: 'oleg_scoot' }, _count: { submissions: 4  } },
]

const surfskate = [
  { id: 501, title: 'БАЗОВЫЙ КАРВИНГ',        trickName: 'CARVING',          difficulty: 'beginner',     description: 'Плавный карвинг в обе стороны на 50+ метров. Оценивается наклон, ритм и плавность дуг.',             prizePoints: 80,  category: 'surfskate', status: 'active', endsAt: d(5),  creator: { username: 'nikita_surf' }, _count: { submissions: 27 } },
  { id: 502, title: 'ФЛОУ В БОУЛУ',           trickName: 'BOWL FLOW',        difficulty: 'beginner',     description: 'Прокат по боулу или волне в парке с несколькими перекладками. Оценивается стиль и линия.',            prizePoints: 100, category: 'surfskate', status: 'active', endsAt: d(4),  creator: { username: 'nikita_surf' }, _count: { submissions: 19 } },
  { id: 503, title: 'CUTBACK НА СКОРОСТИ',    trickName: 'CUTBACK',          difficulty: 'intermediate', description: 'Резкий cutback с потерей скорости и возвратом в волну. Полный разворот с наклоном.',                 prizePoints: 180, category: 'surfskate', status: 'active', endsAt: d(7),  creator: { username: 'nikita_surf' }, _count: { submissions: 12 } },
  { id: 504, title: 'ОФФ-ЗЕ-ЛИП РАЗВОРОТ',   trickName: 'OFF-THE-LIP',      difficulty: 'advanced',     description: 'Въезд на гребень рампы/волны + разворот 180° с возвратом. Оценивается высота и угол.',                prizePoints: 260, category: 'surfskate', status: 'active', endsAt: d(6),  creator: { username: 'nikita_surf' }, _count: { submissions: 7  } },
  { id: 505, title: 'ФЛОУ КОМБО PRO',         trickName: 'FLOW COMBO',       difficulty: 'pro',          description: 'Комбо из 5+ элементов: карвинг, cutback, snap, off-the-lip, разгон. Без остановок, стильно.',         prizePoints: 350, category: 'surfskate', status: 'active', endsAt: d(14), creator: { username: 'nikita_surf' }, _count: { submissions: 3  } },
]

const run = [
  { id: 601, title: 'ПЕРВЫЕ 5 КМ',            trickName: 'RUN 5KM',          difficulty: 'beginner',     description: 'Пробеги 5 км без остановок в любом темпе. Зафиксируй трек в Strava или Garmin.',                      prizePoints: 80,  category: 'run', status: 'active', endsAt: d(7),  creator: { username: 'maxim_run' }, _count: { submissions: 51 } },
  { id: 602, title: 'ТЕМПОВЫЙ БЕГ 5 КМ',      trickName: '5KM SUB-30',       difficulty: 'intermediate', description: 'Пробеги 5 км быстрее 30 минут. Средний темп — не более 6:00 мин/км. Чистый результат без пауз.',      prizePoints: 160, category: 'run', status: 'active', endsAt: d(5),  creator: { username: 'maxim_run' }, _count: { submissions: 33 } },
  { id: 603, title: '10 КМ ЗА 60 МИНУТ',      trickName: '10KM SUB-60',      difficulty: 'advanced',     description: 'Дистанция 10 км, темп — не медленнее 6:00 мин/км. Трейл и шоссе засчитываются.',                      prizePoints: 250, category: 'run', status: 'active', endsAt: d(6),  creator: { username: 'maxim_run' }, _count: { submissions: 19 } },
  { id: 604, title: 'ТРЕЙЛОВЫЙ ЗАБЕГ',         trickName: 'TRAIL RUN',        difficulty: 'intermediate', description: 'Пробеги 8+ км по пересечённой местности (лес, горы). Набор высоты от 100м. Видео с маршрута.',        prizePoints: 200, category: 'run', status: 'active', endsAt: d(10), creator: { username: 'maxim_run' }, _count: { submissions: 22 } },
  { id: 605, title: 'ПОЛУМАРАФОН SUB-2H',      trickName: 'HALF MARATHON',    difficulty: 'pro',          description: 'Полумарафон (21.1 км) быстрее 2 часов. Официальный старт или верифицированный трек.',                 prizePoints: 400, category: 'run', status: 'active', endsAt: d(14), creator: { username: 'maxim_run' }, _count: { submissions: 8  } },
  { id: 606, title: 'СПРИНТ 400М',             trickName: 'SPRINT 400M',      difficulty: 'advanced',     description: 'Пробеги 400м на стадионе или разметке. Таймер с точностью до секунды. Цель — до 1:30.',              prizePoints: 220, category: 'run', status: 'active', endsAt: d(4),  creator: { username: 'maxim_run' }, _count: { submissions: 14 } },
]

const outdoor = [
  { id: 701, title: 'УЛОВ ДНЯ',               trickName: 'CATCH OF THE DAY',  difficulty: 'beginner',     description: 'Сфоткай самую большую рыбу пойманную сегодня. AI оценит размер, вид и технику вываживания.',    prizePoints: 80,  category: 'outdoor', status: 'active', endsAt: d(7),  creator: { username: 'fisher_max' }, _count: { submissions: 43 } },
  { id: 702, title: 'ПРЫЖОК В ВОДУ',           trickName: 'WATER JUMP',        difficulty: 'beginner',     description: 'Прыжок с берега, пирса или скалы в естественный водоём. Снимай в воздухе сбоку.',             prizePoints: 100, category: 'outdoor', status: 'active', endsAt: d(5),  creator: { username: 'outdoor_ira' }, _count: { submissions: 38 } },
  { id: 703, title: 'ЗАКАТ СЕЗОНА',            trickName: 'GOLDEN HOUR',       difficulty: 'beginner',     description: 'Сфоткай самый красивый закат с природы. AI оценит цвета, горизонт и настроение кадра.',       prizePoints: 90,  category: 'outdoor', status: 'active', endsAt: d(4),  creator: { username: 'outdoor_ira' }, _count: { submissions: 61 } },
  { id: 704, title: 'САМОЕ ВЫСОКОЕ ДЕРЕВО',    trickName: 'TREE HUNTER',       difficulty: 'intermediate', description: 'Найди и сфоткай самое высокое дерево в лесу или парке. AI определит породу и оценит высоту.',  prizePoints: 150, category: 'outdoor', status: 'active', endsAt: d(6),  creator: { username: 'nature_serg' }, _count: { submissions: 17 } },
  { id: 705, title: 'ПРЫЖОК С ТАРЗАНКИ',       trickName: 'ROPE SWING',        difficulty: 'intermediate', description: 'Прыжок на верёвке над водой или склоном. Снимай с земли сбоку, чтобы был виден полёт.',        prizePoints: 180, category: 'outdoor', status: 'active', endsAt: d(8),  creator: { username: 'outdoor_ira' }, _count: { submissions: 25 } },
  { id: 706, title: 'ТРЕЙЛ НАХОДКА',           trickName: 'TRAIL DISCOVERY',   difficulty: 'advanced',     description: 'Найди необычный объект на природе — гриб, камень, вид, животное. Сфоткай в контексте.',        prizePoints: 200, category: 'outdoor', status: 'active', endsAt: d(10), creator: { username: 'nature_serg' }, _count: { submissions: 14 } },
  { id: 707, title: 'РЫБАЛКА В НОЧЬ',          trickName: 'NIGHT FISHING',     difficulty: 'advanced',     description: 'Ночная рыбалка — покажи снасти, водоём и улов. AI оценит условия и результат.',               prizePoints: 220, category: 'outdoor', status: 'active', endsAt: d(7),  creator: { username: 'fisher_max' }, _count: { submissions: 9  } },
  { id: 708, title: 'ДАЙВ С ТРЁХМЕТРОВКИ PRO', trickName: 'HIGH DIVE',         difficulty: 'pro',          description: 'Прыжок в воду с высоты 3+ метров. Любой стиль — солдатик, ласточка, кувырок. Снимай сбоку.',  prizePoints: 350, category: 'outdoor', status: 'active', endsAt: d(14), creator: { username: 'outdoor_ira' }, _count: { submissions: 6  } },
]

const physical = [
  { id: 801, title: 'ШПАГАТ ГОРИЗОНТАЛЬНЫЙ',   trickName: 'SPLITS',            difficulty: 'beginner',     description: 'Сфоткай свой горизонтальный шпагат. AI оценит угол между ногами — цель 180°.',                prizePoints: 80,  category: 'physical', status: 'active', endsAt: d(5),  creator: { username: 'fitness_kate' }, _count: { submissions: 49 } },
  { id: 802, title: 'ОТЖИМАНИЯ 30 РАЗ',        trickName: 'PUSH-UPS 30',       difficulty: 'beginner',     description: 'Сними видео 30 чистых отжиманий без остановки. AI считает повторы и оценивает технику.',       prizePoints: 100, category: 'physical', status: 'active', endsAt: d(4),  creator: { username: 'fitness_kate' }, _count: { submissions: 67 } },
  { id: 803, title: 'ПРЫЖОК В ДЛИНУ',          trickName: 'LONG JUMP',         difficulty: 'beginner',     description: 'Прыгни с места в длину и покажи результат. AI оценит технику разбега и приземление.',          prizePoints: 90,  category: 'physical', status: 'active', endsAt: d(6),  creator: { username: 'sport_max' },   _count: { submissions: 31 } },
  { id: 804, title: 'КОЛЕСО',                  trickName: 'CARTWHEEL',         difficulty: 'intermediate', description: 'Покажи чистое колесо — обе ноги прямые, руки касаются земли последовательно.',               prizePoints: 160, category: 'physical', status: 'active', endsAt: d(7),  creator: { username: 'fitness_kate' }, _count: { submissions: 22 } },
  { id: 805, title: 'СТОЙКА НА РУКАХ 5 СЕК',   trickName: 'HANDSTAND 5S',      difficulty: 'intermediate', description: 'Удержи стойку на руках минимум 5 секунд у стены или без. AI засечёт время.',                  prizePoints: 200, category: 'physical', status: 'active', endsAt: d(8),  creator: { username: 'sport_max' },   _count: { submissions: 15 } },
  { id: 806, title: 'САЛЬТО НАЗАД',            trickName: 'BACK FLIP',         difficulty: 'advanced',     description: 'Чистое сальто назад с места или с небольшого разбега. Снимай сбоку, чтобы AI видел обкрут.', prizePoints: 300, category: 'physical', status: 'active', endsAt: d(10), creator: { username: 'sport_max' },   _count: { submissions: 8  } },
  { id: 807, title: 'РАЗМИНКА ПРЫЖКАМИ',       trickName: 'JUMP CIRCUIT',      difficulty: 'beginner',     description: 'Серия из 10 прыжков со скакалкой или на месте. AI оценит ритм и высоту.',                      prizePoints: 70,  category: 'physical', status: 'active', endsAt: d(3),  creator: { username: 'fitness_kate' }, _count: { submissions: 88 } },
  { id: 808, title: 'ФЛИК-ФЛАК PRO',           trickName: 'BACK HANDSPRING',   difficulty: 'pro',          description: 'Флик-флак — прыжок назад с опорой на руки и возвратом в стойку. Только для гимнастов.',       prizePoints: 380, category: 'physical', status: 'active', endsAt: d(14), creator: { username: 'sport_max' },   _count: { submissions: 4  } },
]

export const MOCK_CHALLENGES_BY_SPORT: Record<string, any[]> = {
  skate, bmx, rollers, scooter, surfskate, run, outdoor, physical,
}

export const MOCK_CHALLENGES = skate

export const MOCK_CHALLENGES_MAP: Record<number, any> = Object.fromEntries(
  [...skate, ...bmx, ...rollers, ...scooter, ...surfskate, ...run, ...outdoor, ...physical].map(c => [c.id, { ...c }])
)
